#!/usr/bin/env python3
"""Check the published decision ledger. Standard library only, no network.

Usage:
    python ledger/verify_ledger.py            # verify, exit 0 on PASS
    python ledger/verify_ledger.py --write    # regenerate SUMMARY.md and MANIFEST.json (maintainer)

Checks:
  1. DECISIONS.jsonl parses; ids are unique and consecutive (D-001..D-NNN).
  2. Every row states a question, a check and a bar.
  3. Every resolved row (confirmed / refuted / inconclusive) has an outcome and
     a resolved_at timestamp that is not earlier than its stated_at timestamp.
     Open rows have no outcome yet.
  4. The status tally and the file hash match MANIFEST.json.
  5. SUMMARY.md is exactly what this script generates from DECISIONS.jsonl.
"""
import hashlib, json, sys
from collections import Counter
from datetime import datetime
from pathlib import Path

HERE = Path(__file__).resolve().parent
LEDGER, MANIFEST, SUMMARY = HERE / "DECISIONS.jsonl", HERE / "MANIFEST.json", HERE / "SUMMARY.md"
RESOLVED = {"confirmed", "refuted", "inconclusive"}
STATUSES = RESOLVED | {"open"}


def ts(s):
    return datetime.fromisoformat(s.replace("Z", "+00:00"))


def load():
    rows = [json.loads(l) for l in LEDGER.read_text(encoding="utf-8").splitlines() if l.strip()]
    return rows


def check_rows(rows):
    errors = []
    ids = [r["id"] for r in rows]
    expected = [f"D-{i:03d}" for i in range(1, len(rows) + 1)]
    if ids != expected:
        errors.append(f"ids are not unique and consecutive: {ids}")
    for r in rows:
        rid = r["id"]
        if r["status"] not in STATUSES:
            errors.append(f"{rid}: unknown status {r['status']!r}")
        for field in ("question", "check", "bar"):
            if not (r.get(field) or "").strip():
                errors.append(f"{rid}: missing {field}")
        if r["status"] in RESOLVED:
            if not (r.get("outcome") or "").strip():
                errors.append(f"{rid}: resolved without an outcome")
            if not r.get("resolved_at"):
                errors.append(f"{rid}: resolved without resolved_at")
            elif ts(r["resolved_at"]) < ts(r["stated_at"]):
                errors.append(f"{rid}: resolved_at precedes stated_at")
        elif (r.get("outcome") or "").strip():
            errors.append(f"{rid}: open row already has an outcome")
    return errors


def one_line(text, limit):
    text = " ".join((text or "").split())
    return text if len(text) <= limit else text[: limit - 3].rstrip() + "..."


def summary(rows):
    tally = Counter(r["status"] for r in rows)
    first, last = rows[0]["stated_at"][:16], rows[-1]["stated_at"][:16]
    out = [
        "# Decision ledger summary",
        "",
        "Generated by `verify_ledger.py --write` from `DECISIONS.jsonl`. Do not edit by hand.",
        "",
        f"{len(rows)} preregistered decisions, stated {first}Z to {last}Z (UTC).",
        "",
        "| Status | Count |",
        "|---|---|",
    ]
    for s in ("confirmed", "refuted", "inconclusive", "open"):
        out.append(f"| {s} | {tally.get(s, 0)} |")
    out += ["", "| ID | Stated (UTC) | Status | Question | Bar | Outcome |", "|---|---|---|---|---|---|"]
    for r in rows:
        cells = [
            r["id"], r["stated_at"][:16].replace("T", " "), r["status"],
            one_line(r["question"], 160), one_line(r["bar"], 140),
            one_line(r["outcome"], 220) if r["outcome"] else "(pending)",
        ]
        out.append("| " + " | ".join(c.replace("|", "/") for c in cells) + " |")
    return "\n".join(out) + "\n"


def manifest(rows):
    tally = Counter(r["status"] for r in rows)
    return {
        "ledger": "DECISIONS.jsonl",
        "ledger_sha256": hashlib.sha256(LEDGER.read_bytes()).hexdigest(),
        "rows": len(rows),
        "tally": {s: tally.get(s, 0) for s in ("confirmed", "refuted", "inconclusive", "open")},
        "summary_sha256": hashlib.sha256(summary(rows).encode("utf-8")).hexdigest(),
    }


def main():
    rows = load()
    errors = check_rows(rows)
    if "--write" in sys.argv:
        if errors:
            print("\n".join(errors)); return 1
        SUMMARY.write_text(summary(rows), encoding="utf-8", newline="\n")
        m = json.loads(MANIFEST.read_text(encoding="utf-8")) if MANIFEST.exists() else {}
        m.update(manifest(rows))
        MANIFEST.write_text(json.dumps(m, indent=2) + "\n", encoding="utf-8", newline="\n")
        print("wrote SUMMARY.md and MANIFEST.json"); return 0
    m = json.loads(MANIFEST.read_text(encoding="utf-8"))
    want = manifest(rows)
    for k in ("ledger_sha256", "rows", "tally", "summary_sha256"):
        if m.get(k) != want[k]:
            errors.append(f"MANIFEST {k} mismatch: recorded {m.get(k)!r}, computed {want[k]!r}")
    if SUMMARY.read_text(encoding="utf-8") != summary(rows):
        errors.append("SUMMARY.md differs from the generated summary")
    if errors:
        print("FAIL"); print("\n".join(errors)); return 1
    t = want["tally"]
    print(f"PASS: {want['rows']} decisions; confirmed {t['confirmed']}, refuted {t['refuted']}, "
          f"inconclusive {t['inconclusive']}, open {t['open']}; ledger sha256 {want['ledger_sha256']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
